### ISSUE TITLE
BDD complement/negation functionality?

### ISSUE THREAD

**Issue by guyvdbroeck** [sisl/CUDD.jl#16]
I believe the way to negate/complement a BDD is by calling `Cudd_Complement` or `Cudd_Not` in CUDD? That function is not available in CUDD.jl.
Or it could be by manipulating the pointer bits to become complemented, I am not sure, perhaps there can be a native Julia implementation of that?

**Comment by guyvdbroeck** [comment]
This function should work:
```
Cudd_Not(node) =
    convert(Ptr{Nothing}, xor(convert(Int,node), 1))
```

**Comment by guyvdbroeck** [comment]
You might also want to add:
```
Cudd_IsComplement(node) =
    isone(convert(Int,node) & 1)

Cudd_Regular(node) = 
    convert(Ptr{Nothing}, convert(Int,node) & ~1)
```

**Comment by mykelk** [comment]
Sounds good. Would you like to file a PR?
