### ISSUE TITLE
Use Yggdrasil

### ISSUE THREAD

**Issue by blegat** [sisl/CUDD.jl#21]
BinaryProvider seems to be broken on Windows with Julia v1.8, see https://github.com/JuliaPackaging/BinaryProvider.jl/issues/211
One long term fix would be to use Yggdrasil and a CUDD_jll artifact

**Comment by mykelk** [comment]
Sounds good to me. A PR is welcome and we can merge it quickly.

**Comment by blegat** [comment]
Unfortunately, I won't have time to do it in the near term but I can help if needed

**Comment by MaximeBouton** [comment]
I am not too rusty with Yggdrasil so I opened a PR to build CUDD_jll https://github.com/JuliaPackaging/Yggdrasil/pull/5521
